name: Deploy to Railway

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Adjust this if your PRs are targeting a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Build Docker image
        run: |
          docker build -t darkjus/your-railway-app:latest .

      - name: Log in to Railway CLI
        run: |
          curl -sSL https://cli.railway.app/install.sh | sh
          export PATH=$PATH:$HOME/.railway/bin
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        if: github.event_name == 'push'
        run: |
          railway up --service your-railway-service-name

      - name: PR Deployment Confirmation
        if: github.event_name == 'pull_request'
        run: echo "Pull Request Triggered: No deployment will occur."
 