name: Deploy to Railway

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Adjust this if your PRs are targeting a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (3.12)
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Railway CLI Manually
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget -q https://cli.railway.app/railway-linux-amd64 -O /usr/local/bin/railway
          sudo chmod +x /usr/local/bin/railway
          echo 'export PATH="/usr/local/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV
          railway --version

      - name: Authenticate Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN

      - name: Deploy to Railway (Production)
        if: github.event_name == 'push'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --yes

      - name: PR Deployment Confirmation
        if: github.event_name == 'pull_request'
        run: |
          echo "Pull Request Triggered: No deployment will occur."
